import { randomInt, secureString, uuidV4, digest, makeTestData, copyText } from './js/utils.js';

const tools = [
  ['number', '#', 'Random Number', 'Random', 'Números inteiros em intervalos configuráveis.'], ['password', '⌁', 'Password Generator', 'Security', 'Senhas fortes geradas com Web Crypto.'], ['uuid', '◇', 'UUID Generator', 'Developer', 'UUID v4 para aplicações e ambientes.'], ['hash', '#', 'Hash Generator', 'Developer', 'SHA-256 e SHA-512 no navegador.'], ['string', 'Aa', 'String Generator', 'Security', 'Strings para tokens, mocks e IDs.'], ['testdata', '{}', 'Test Data', 'Testing', 'Dados fictícios para testar com segurança.'],
];
const workspace = document.querySelector('#workspace');
const historyKey = 'devtools-recent-v1';

function init() {
  renderToolCards(); bindGlobalUI();
  document.querySelector('#previewGenerate').addEventListener('click', () => { document.querySelector('#previewResult').textContent = String(randomInt(0, 9999)).padStart(4, '0'); });
  setTheme(localStorage.getItem('devtools-theme') || 'dark');
  const requested = location.hash.slice(1); if (tools.some(([id]) => id === requested)) openTool(requested);
}
function bindGlobalUI() {
  document.querySelector('.theme-toggle').addEventListener('click', () => setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'));
  const toggle = document.querySelector('.menu-toggle'); toggle.addEventListener('click', () => { const open = document.querySelector('.nav-links').classList.toggle('open'); toggle.setAttribute('aria-expanded', String(open)); toggle.setAttribute('aria-label', open ? 'Fechar menu' : 'Abrir menu'); });
  document.querySelector('#toolGrid').addEventListener('click', event => { const button = event.target.closest('[data-tool]'); if (button) openTool(button.dataset.tool); });
}
function setTheme(theme) { document.documentElement.dataset.theme = theme; document.querySelector('.theme-label').textContent = theme === 'dark' ? 'Light' : 'Dark'; localStorage.setItem('devtools-theme', theme); }
function renderToolCards() { document.querySelector('#toolGrid').innerHTML = tools.map(([id, icon, name, category, description]) => `<button class="tool-card" type="button" data-tool="${id}"><span class="tool-icon" aria-hidden="true">${icon}</span><span class="tool-category">${category}</span><strong>${name}</strong><span>${description}</span><em>Open <b aria-hidden="true">→</b></em></button>`).join(''); }
function openTool(id) { location.hash = id; const view = { number: numberView, password: passwordView, uuid: uuidView, hash: hashView, string: stringView, testdata: testDataView }[id]; workspace.innerHTML = `<div class="workspace-top"><button class="back-button" type="button">← All tools</button><span>${tools.find(t => t[0] === id)[3].toUpperCase()}</span></div>${view()}${historyView()}`; workspace.querySelector('.back-button').addEventListener('click', closeTool); bindTool(id); bindHistory(); workspace.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' }); }
function closeTool() { history.replaceState(null, '', '#tools'); workspace.innerHTML = ''; document.querySelector('#tools').scrollIntoView({ behavior: 'smooth' }); }
const field = (id, label, value, attrs = '') => `<div class="field"> <label for="${id}">${label}</label><input id="${id}" value="${value}" ${attrs}></div>`;
function panel(title, description, content) { return `<article class="tool-panel"><header><p class="eyebrow">UTILITY</p><h2>${title}</h2><p>${description}</p></header>${content}</article>`; }
function resultBox(value = '—', multiline = false) { return `<div class="result-area"><div class="result-head"><span>RESULT</span><button class="copy-button" type="button" data-copy aria-label="Copiar resultado">Copy</button></div><output class="tool-result${multiline ? ' multiline' : ''}" data-result>${value}</output></div>`; }
function historyView() { const recent = JSON.parse(localStorage.getItem(historyKey) || '[]'); return `<aside class="history-panel"><div class="result-head"><span>RECENT</span><button class="copy-button" type="button" data-clear-history>Clear</button></div>${recent.length ? `<ul>${recent.slice(0, 5).map((entry, index) => `<li><button type="button" data-history="${index}" title="Copiar resultado recente">${entry.value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('\n', ' · ')}</button></li>`).join('')}</ul>` : '<p>Nenhum resultado recente neste dispositivo.</p>'}</aside>`; }
function numberView() { return panel('Random Number', 'Gere números inteiros com uma fonte de aleatoriedade segura.', `<form class="tool-form" data-form="number"><div class="field-row">${field('min', 'Minimum', '1', 'type="number" step="1" required')}${field('max', 'Maximum', '100', 'type="number" step="1" required')}${field('quantity', 'Quantity', '1', 'type="number" min="1" max="100" required')}</div><label class="check"><input id="duplicates" type="checkbox" checked> Allow duplicates</label><p class="form-message" data-message role="alert"></p><button class="button primary" type="submit">Generate</button></form>${resultBox()}`); }
function passwordView() { return panel('Password Generator', 'Senhas criadas localmente usando Web Crypto.', `<form class="tool-form" data-form="password"><label for="passwordLength">Length <output id="lengthValue">20</output></label><input id="passwordLength" type="range" min="8" max="64" value="20"><div class="check-grid"><label class="check"><input type="checkbox" value="upper" checked> Uppercase</label><label class="check"><input type="checkbox" value="lower" checked> Lowercase</label><label class="check"><input type="checkbox" value="number" checked> Numbers</label><label class="check"><input type="checkbox" value="symbol" checked> Symbols</label></div><p class="form-message" data-message role="alert"></p><button class="button primary" type="submit">Generate</button></form><div class="strength"><span>Strength</span><div><i></i><i></i><i></i><i></i></div><b data-strength>Strong</b></div>${resultBox()}`); }
function uuidView() { return panel('UUID Generator', 'Crie identificadores UUID v4 em instantes.', `<form class="tool-form" data-form="uuid"><div class="field"><label for="uuidVersion">Version</label><select id="uuidVersion"><option>UUID v4</option></select></div><button class="button primary" type="submit">Generate</button></form>${resultBox()}`); }
function hashView() { return panel('Hash Generator', 'Hashes de uma via, úteis para integridade e identificação.', `<form class="tool-form" data-form="hash"><label for="hashInput">Input</label><textarea id="hashInput" rows="4" placeholder="Digite ou cole o texto para gerar o hash"></textarea><div class="field"><label for="algorithm">Algorithm</label><select id="algorithm"><option value="SHA-256">SHA-256</option><option value="SHA-512">SHA-512</option></select></div><p class="form-message" data-message role="alert"></p><button class="button primary" type="submit">Generate</button></form>${resultBox('—', true)}<p class="hint">Hash não é criptografia. Hashes são funções de mão única usadas para integridade, identificação e outras aplicações.</p>`); }
function stringView() { return panel('String Generator', 'Strings seguros para tokens temporários, IDs e massa de teste.', `<form class="tool-form" data-form="string">${field('stringLength', 'Length', '32', 'type="number" min="1" max="512" required')}<div class="check-grid"><label class="check"><input type="checkbox" value="upper" checked> A-Z</label><label class="check"><input type="checkbox" value="lower" checked> a-z</label><label class="check"><input type="checkbox" value="number" checked> 0-9</label><label class="check"><input type="checkbox" value="symbol"> Symbols</label></div><p class="form-message" data-message role="alert"></p><button class="button primary" type="submit">Generate</button></form>${resultBox()}`); }
function testDataView() { return panel('Test Data Generator', 'Dados deliberadamente fictícios para ambientes de teste.', `<form class="tool-form" data-form="testdata"><fieldset><legend>Generate</legend><div class="radio-grid">${['Name', 'Email', 'Phone', 'Date', 'Address', 'Username', 'Number'].map((item, i) => `<label class="check"><input type="radio" name="dataType" value="${item.toLowerCase()}" ${i === 0 ? 'checked' : ''}> ${item}</label>`).join('')}</div></fieldset>${field('testQuantity', 'Quantity', '10', 'type="number" min="1" max="50" required')}<p class="form-message" data-message role="alert"></p><button class="button primary" type="submit">Generate</button></form>${resultBox('—', true)}`); }
function bindTool(id) {
  const form = workspace.querySelector('form'), result = workspace.querySelector('[data-result]'), message = workspace.querySelector('[data-message]'); workspace.querySelector('[data-copy]').addEventListener('click', () => copyResult(result));
  if (id === 'password') workspace.querySelector('#passwordLength').addEventListener('input', e => workspace.querySelector('#lengthValue').textContent = e.target.value);
  form.addEventListener('submit', async event => { event.preventDefault(); message.textContent = ''; try { let value, shouldSave = id !== 'password';
    if (id === 'number') { const min = +workspace.querySelector('#min').value, max = +workspace.querySelector('#max').value, quantity = +workspace.querySelector('#quantity').value, duplicates = workspace.querySelector('#duplicates').checked; if (!Number.isInteger(min) || !Number.isInteger(max) || min > max || quantity < 1) throw Error('Informe um intervalo inteiro válido.'); if (!duplicates && quantity > max - min + 1) throw Error('A quantidade é maior que os valores únicos disponíveis.'); const values = []; while (values.length < quantity) { const n = randomInt(min, max); if (duplicates || !values.includes(n)) values.push(n); } value = values.join('\n'); }
    if (id === 'password' || id === 'string') { const selected = [...form.querySelectorAll('input[type="checkbox"]:checked')].map(x => x.value); if (!selected.length) throw Error('Selecione ao menos um grupo de caracteres.'); const length = +(id === 'password' ? workspace.querySelector('#passwordLength').value : workspace.querySelector('#stringLength').value); value = secureString(length, selected); }
    if (id === 'uuid') value = uuidV4(); if (id === 'hash') { const input = workspace.querySelector('#hashInput').value; if (!input) throw Error('Digite um valor para gerar o hash.'); value = await digest(input, workspace.querySelector('#algorithm').value); } if (id === 'testdata') value = makeTestData(form.querySelector('input[name="dataType"]:checked').value, +workspace.querySelector('#testQuantity').value).join('\n'); result.textContent = value; result.classList.remove('fresh'); void result.offsetWidth; result.classList.add('fresh'); if (shouldSave) addHistory(id, value);
  } catch (error) { message.textContent = error.message; } });
}
function bindHistory() {
  const clear = workspace.querySelector('[data-clear-history]');
  clear.addEventListener('click', () => { localStorage.removeItem(historyKey); workspace.querySelector('.history-panel').outerHTML = historyView(); bindHistory(); });
  workspace.querySelectorAll('[data-history]').forEach(button => button.addEventListener('click', async () => { const value = JSON.parse(localStorage.getItem(historyKey) || '[]')[button.dataset.history]?.value; if (value) { await copyText(value); showToast('Resultado recente copiado.'); } }));
}
async function copyResult(output) { if (!output.textContent || output.textContent === '—') return; await copyText(output.textContent); showToast('Copiado para a área de transferência.'); }
function addHistory(type, value) { const recent = JSON.parse(localStorage.getItem(historyKey) || '[]'); recent.unshift({ type, value: value.slice(0, 240), at: Date.now() }); localStorage.setItem(historyKey, JSON.stringify(recent.slice(0, 20))); const panel = workspace.querySelector('.history-panel'); if (panel) { panel.outerHTML = historyView(); bindHistory(); } }
function showToast(text) { const toast = document.querySelector('#toast'); toast.textContent = text; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
init();
